clear;
resetAndLoad;

fakeViewsByPsych(nSharesPopulationStruct);
trueViewsByPsych(nSharesPopulationStruct);
totalViewsByPsych(nSharesPopulationStruct);
fakeSharesByPsych(nSharesPopulationStruct);
trueSharesByPsych(nSharesPopulationStruct);
totalSharesByPsych(nSharesPopulationStruct);