clear;
scriptPath = fileparts(mfilename('fullpath'));
cd (scriptPath);
timesList = loadTimes(scriptPath);
lastTime = size(timesList);
lastTime = lastTime(1);
desiredSim = timesList{lastTime};
%nSharedFakeNews;
nSharesPopulationStruct = nSharesPopulationFunc();
nSharesAllStruct = importCSV('nSharesAll');
nViewsAllStruct = importCSV('nViewsAll');
% viewersAllStruct = importCSV('viewersAll');
% sharersAllStruct = importCSV('sharersAll');
newsInfoStruct = importCSV('newsInfo');