clear;
scriptPath = fileparts(mfilename('fullpath'));
cd (scriptPath);
timesList = loadTimes(scriptPath);
lastTime = size(timesList);
lastTime = lastTime(1);
desiredSim = timesList{lastTime};
%nSharedFakeNews;
nSharesPopulationStruct = nSharesPopulationFunc(desiredSim);
nSharesAllStruct = importCSV('nSharesAll', desiredSim);
nViewsAllStruct = importCSV('nViewsAll', desiredSim);
% viewersAllStruct = importCSV('viewersAll', desiredSim);
% sharersAllStruct = importCSV('sharersAll', desiredSim);
newsInfoStruct = importCSV('newsInfo', desiredSim);